# Generated by Django 4.2.2 on 2023-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('short_break', models.CharField(max_length=50)),
                ('long_break', models.CharField(max_length=50)),
                ('schedule', models.TextField()),
            ],
        ),
    ]
