# Generated by Django 4.2.2 on 2023-06-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
