# Generated by Django 4.2.2 on 2023-06-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hasSubmittedImages',
            field=models.ImageField(upload_to='student_images/'),
        ),
    ]
