# Generated by Django 4.2.2 on 2023-06-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
