# Generated by Django 4.2.2 on 2023-06-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_hassubmittedimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hasSubmittedImages',
            new_name='image',
        ),
    ]
